### ISSUE TITLE
March to 2.0!

### ISSUE THREAD

**Issue by baetheus** [baetheus/fun#132]
This is a parent issue for all the necessary work to get functional to version 2.0. The progress of which will generally be tracked in my "Deno" project [here](https://github.com/users/baetheus/projects/2/views/2).

At a high level the following tasks need to be done:

- [x] 1. Finish up the initial flake work for reproducible builds
- [x] 2. Finish up the initial node build work for broader access
- [x] 3. Clean up some of the rough edges that I had been working on
- [x] 4. Go through the whole library module by module to implement: missing functionality, documentation, and tests
- [x] 5. Create a few quality of life scripts used to manage README, mod.ts, and the fun book (future work)
- [x] 6. Button down the last of the CI/CD work
- [x] 7. Release!

The features that are put on hold while this work is completed are:

- Observables
- ADT over raw Promise (with some broken laws because we are ultimately beholden in js-land)
- Parsing and lexing tools

**Comment by pixeleet** [comment]
Glad to see you're active again! Feel free to drop some issues my way and let's catch up.

**Comment by baetheus** [comment]
Version 2.0 is out!
