### ISSUE TITLE
Module not found "https://deno.land/x/fun@v2.0.0-alpha.10/decode_error.ts"

### ISSUE THREAD

**Issue by denizdogan** [baetheus/fun#170]
I think there's a missing module in the v2.0.0-alpha.10 as it exists on deno.land right now.

```console
❯ deno cache -r --unstable experiment.ts
error: Module not found "https://deno.land/x/fun@v2.0.0-alpha.10/decode_error.ts".
    at https://deno.land/x/fun@v2.0.0-alpha.10/mod.ts:14:31
```

Could you please publish a new version? The fix for this is not available on GitHub, and I wasn't able to download the latest main branch from Fossil.

**Comment by baetheus** [comment]
Sure, I often forget about mod.ts since I don't normally use it.

**Comment by pixeleet** [comment]
I remember adding it originally, and it turns out it's useless, we should import directly from `fun/module.ts` instead of doing `import { either } from 'fun/mod.ts'` so probably we should delete it next release? 

@baetheus are you active again my friend?

**Comment by baetheus** [comment]
Fixed in cfbca397e60b1433f49f7003002c26480effb285

**Comment by baetheus** [comment]
@pixeleet Haha, I'm hoping on a plane to London tomorrow morning and will be without a laptop for 6 weeks :D.

If you find yourself with time to meet up I'll be in the UK or Spain until June 15th.

**Comment by pixeleet** [comment]
@baetheus leave me some contact details in zulip or mail where I can reach you :) I'm in Spain so should be easy to grab some tapas.

**Comment by baetheus** [comment]
@denizdogan Just an FYI, if you ever find that mod.ts is broken again there is a script at `scripts/mod.sh`. You can fork fun and run `./scripts/mod.sh > mod.ts` from the root dir to fix it. I'm only bringing this up since I'll be unable to fix other stuff (although test coverage is high so nothing *should* be broken) for a bit.

**Comment by denizdogan** [comment]
@baetheus Thank you! :)

**Comment by denizdogan** [comment]
Just in case anyone else encounters the same problem when updating the dependency version:

The tag was accidentally named `v.2.0.0-alpha.11` – read that carefully :)

```
https://deno.land/x/fun@v.2.0.0-alpha.11/mod.ts
   there's a period here ^
```

It took me way too long to figure that out.

Thanks again!

**Comment by baetheus** [comment]
Haha, that’s what I get for rushing!On Apr 30, 2023, at 11:43 AM, Deniz ***@***.***> wrote:﻿
Just in case anyone else encounters the same problem when updating the dependency version:
The tag was accidentally named v.2.0.0-alpha.11 – read that carefully :)
***@***.***/mod.ts
   there's a period here ^

It took me way too long to figure that out.
Thanks again!

**Comment by pixeleet** [comment]
`decode_error.ts` has been merged into `decoder.ts`.
`mod.ts` was removed. closing issue.
