### ISSUE TITLE
Async flow?

### ISSUE THREAD

**Issue by denizdogan** [baetheus/fun#173]
What would be a good way to get `flow` to work async? In other words, something like this:

```ts
// (a: A) => Promise<D>
const foo = asyncFlow(
  ab, // (a: A) => Promise<B>
  bc, // (b: B) => Promise<C>
  cd, // (c: C) => Promise<D>
)

const d = await foo(a)
```

I've been at it for hours, but I can't realize it without pretty much reimplementing `flow` but with Promises everywhere.

Ideas?

**Comment by baetheus** [comment]
You could use chain from promise.ts

```ts
import { flow } from "../fn.ts";
import * as P from "../promise.ts";

const asyncAddOne = (n: number) => P.of(n + 1);

const test = flow(
  (n: number) => P.of(n),
  P.chain(asyncAddOne),
); // (n: number) => Promise<number>
```

**Comment by denizdogan** [comment]
@baetheus Thanks for your swift response, much appreciated!

I think I was looking for a way to basically map `P.chain` on every argument passed to `flow`. That way, users of this imaginary function `flow'` could pass either async or sync functions into it, and it would look like they just magically work together regardless. I'm thinking something along the lines of:

```ts
// obviously doesn't work
const flow' = (...args: unknown[]) => flow(...args.map((a) => T.of(a)))
```

Would such a thing even be possible?

**Comment by baetheus** [comment]
Yes, definitely possible.

I'm sure you've looked at the implementation of flow:

```ts
// type overloading removed
export function flow(
  ...[ab, bc, cd, de, ef, fg, gh, hi, ij, jk, kl, ...rest]: AnyFn[]
): AnyFn {
  switch (arguments.length) {
    case 1:
      return (...as) => ab(...as);
    case 2:
      return (...as) => bc(ab(...as));
    case 3:
      return (...as) => cd(bc(ab(...as)));
    case 4:
      return (...as) => de(cd(bc(ab(...as))));
    case 5:
      return (...as) => ef(de(cd(bc(ab(...as)))));
    case 6:
      return (...as) => fg(ef(de(cd(bc(ab(...as))))));
    case 7:
      return (...as) => gh(fg(ef(de(cd(bc(ab(...as)))))));
    case 8:
      return (...as) => hi(gh(fg(ef(de(cd(bc(ab(...as))))))));
    case 9:
      return (...as) => ij(hi(gh(fg(ef(de(cd(bc(ab(...as)))))))));
    case 10:
      return (...as) => jk(ij(hi(gh(fg(ef(de(cd(bc(ab(...as))))))))));
    case 11:
      return (...as) => kl(jk(ij(hi(gh(fg(ef(de(cd(bc(ab(...as)))))))))));
    default:
      return (...as) =>
        rest.reduce(
          (val, fn) => fn(val),
          kl(jk(ij(hi(gh(fg(ef(de(cd(bc(ab(...as))))))))))),
        );
  }
}
```

You could take this format and add an await before every function invocation (ie. `return (...as) => await bc(await ab(...as));`). You'd have to also update all the overloadings to accept `A | PromiseLike<A>`. And the return type of this `flow'` would always be a promise, as there is no "clean" way to type or implement a function that sometimes returns a promise and sometimes returns a non-promise.

Personally, I have found, anecdotally of course, that production code tends to run into fewer pathological cases when you stick to monomorphic (meaning single type shapes, ie always returns/takes a promise or always returns/takes a non-promise). The advantage of the types of functions that you are trying to make is that they try to infer the programmer's intent by being both specialized and generic. They aren't as generic as the existing flow, which makes them specific, but they are more generic than a version of flow that only accepts async functions.

That said, I think it's good that you're exploring these patterns and looking for ways to simplify. Let me know if you come up with anything else you think is interesting or need some feedback on!

**Comment by denizdogan** [comment]
Thanks again 🙏
